### PR TITLE
[JENKINS-49635] Using ArtifactManagerTest

### PR DESCRIPTION
**Pull request by jglick**
Integrates with https://github.com/jenkinsci/workflow-api-plugin/pull/67 and https://github.com/jenkinsci/jenkins/pull/3302.

- [X] running a smoke test
- [x] using new `list` overload

### CODE REVIEW

**Comment by olivergondza** [comment]
As this does not seem to have any effect on productions code (or does it?), I suggest to postpone the merge not to rise the core dependency too high.

**Comment by jglick** [comment]
I am not proposing any immediate merge.

**Comment by jglick** [comment]
> I am not proposing any immediate merge.

But 2–3 years later?

**Comment by olivergondza** [comment]
Thanks, @jglick!

**Pull request merged**
